name: 'Pull Request'
on: ['pull_request']

env:
  RUST_BACKTRACE: 'full'

jobs:
  build:
    name: 'Debug Build'
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v2'
    - name: 'Install Stable Toolchain'
      uses: 'actions-rs/toolchain@v1'
      with:
        toolchain: 'stable'
        target: 'x86_64-unknown-linux-musl'
        profile: 'minimal'
        components: 'clippy'

    - name: 'Login to Docker Hub'
      uses: 'docker/login-action@v1'
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: 'Cache Rust Targets'
      uses: 'actions/cache@v2'
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: 'Debug Build'
      run: 'cargo build'

  test-minimal:
    name: 'Cargo Test (--no-default-features)'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
    - uses: 'actions/checkout@v2'
    - name: 'Cache Rust Targets'
      uses: 'actions/cache@v2'
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          ${{ runner.os }}-cargo-

    - run: 'cargo test --no-default-features --'

  test:
    name: 'Cargo Test'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
    - uses: 'actions/checkout@v2'
    - name: 'Cache Rust Targets'
      uses: 'actions/cache@v2'
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          ${{ runner.os }}-cargo-

    - run: id
    - run: 'cargo test --'

  checks:
    name: 'Other Cargo Checks'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
    - uses: 'actions/checkout@v2'
    - name: 'Cache Rust Targets'
      uses: 'actions/cache@v2'
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          ${{ runner.os }}-cargo-

    - run: 'cargo clippy'
    - run: 'cargo doc --no-deps'
